title: Unitarian Universalists of Rossmoor
description: A welcoming Unitarian Universalist fellowship in Rossmoor, Walnut Creek, CA. Join us Fridays for programs on spirituality, justice and community.
baseurl: "" # Leave empty for root directory
url: "https://rossmooruu.org" # Your website URL

# Build settings
plugins:
  - jekyll-sitemap

# Exclude files and directories from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# GitHub Pages settings
github:
  is_project_page: false
